### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by analytically** [herdstat/herdstat#45]
Analysing 8 private repo's resulted in a panic:

<img width="829" alt="screenshot 2023-03-20 at 17 53 58@2x" src="https://user-images.githubusercontent.com/254434/226425825-1133a48c-075b-4fe3-a4e0-564ae0da67bf.png">

**Comment by strieflinger** [comment]
Just released a bug fix release that might resolve the issue: #43. Can you please give `herdstat` [v0.9.1](https://github.com/herdstat/herdstat/releases/tag/v0.9.1) a try?

**Comment by analytically** [comment]
Seen that the github action pulls in latest. Tried with that and works!
