### ISSUE TITLE
Add day of week to tooltip

### ISSUE THREAD

**Issue by analytically** [herdstat/herdstat#48]
Would be good to know the day of week in tooltip :-)

**Comment by strieflinger** [comment]
Hi @analytically, that functionality is actually implemented (see screenshot below). Unfortunately, the strict security sandbox of GitHub doesn't allow to use that functionality when the SVG is embedded into markdown pages, like the `README.md`as shown in the example repo. You can see the tooltips in action by opening the SVG directly in a browser. Probably `herdstat` will allow to generate a website in the future that shows the contribution graph and other visualizations of OSS community metrics.

<img width="700" alt="Screenshot 2023-03-22 at 19 44 32" src="https://user-images.githubusercontent.com/31168258/227006663-61fb0eae-7e2a-4d14-91e3-57c78463e5f4.png">
